version: '3.3'
services:
  bcf-docker-api-service:
    container_name: bcf-docker-api-service
    image: bcf-docker-api-service:0.1
#    env_file:
#      - ./envfile
    environment:
      - SPRING.CLOUD.NACOS.DISCOVERY.URI=192.168.130.109:8082
    ports:
      - "8091:8091"
    volumes:
      - /tmp/gunicorn_socket:/tmp/gunicorn_socket
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/k2data/bcf-deploy-dist-v1.0.0/bcf/app-images:/k2data/images
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 10m
networks:
  default:
    external:
      name: k2data-bcf